name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: self-hosted

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{secrets.JWT_SECRET}}

      REDIS_URL: "redis://localhost:6379"
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      JWT_EXPIRES_IN: "7d"

      WORKER_PORT: 3001
      WORKER_HOST: 0.0.0.0
      WORKER_CONCURRENCY: 1
      
      E2E_API_URL: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "26"

      - name: Install Deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm check-types

      - name: Build
        run: pnpm build

      - name: Unit Tests
        run: pnpm test:unit

      - name: Cleanup workspace
        if: always()
        run: |
          git clean -fdx
          git reset --hard HEAD
